In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
path_train = '/content/drive/MyDrive/Colab_Notebooks/ratings_train.csv'
path_valid = '/content/drive/MyDrive/Colab_Notebooks/ratings_valid.csv'
path_movies = '/content/drive/MyDrive/Colab_Notebooks/movies.csv'


ratings_train = pd.read_csv(path_train)
ratings_valid = pd.read_csv(path_valid)
movies = pd.read_csv(path_movies)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#get mean rating of each movie
avg_rating = ratings_train[['movieId', 'rating']].groupby(by='movieId').mean()
#get mean rating of each user
avg_rating_of_person = ratings_train[['userId','rating']].groupby(by='userId').mean()

In [ ]:
#rename mean rating of each movie
avg_rating.rename(columns = {'rating':'avg_rating_of_movie'}, inplace = True)
avg_rating

avg_rating_of_movie
movieId                     
1                   3.920930
2                   3.431818
3                   3.259615
4                   2.357143
5                   3.090909
...                      ...
193581              4.000000
193583              3.500000
193585              3.500000
193587              3.500000
193609              4.000000

[9690 rows x 1 columns]

In [ ]:
#rename mean rating of each user
avg_rating_of_person.rename(columns = {'rating':'avg_rating_of_person'}, inplace = True)
avg_rating_of_person

avg_rating_of_person
userId                      
1                   4.366379
2                   3.948276
3                   2.435897
4                   3.588235
5                   3.636364
...                      ...
606                 3.657399
607                 3.786096
608                 3.134176
609                 3.270270
610                 3.688556

[610 rows x 1 columns]

In [ ]:
train_set = pd.merge(ratings_train,avg_rating_of_person,on='userId')
train_set = pd.merge(train_set,avg_rating,on='movieId')
train_set

userId  movieId  rating   timestamp  avg_rating_of_person  \
0           1        1     4.0   964982703              4.366379   
1           5        1     4.0   847434962              3.636364   
2           7        1     4.5  1106635946              3.230263   
3          15        1     2.5  1510577970              3.448148   
4          17        1     4.5  1305696483              4.234375   
...       ...      ...     ...         ...                   ...   
96459     610   160341     2.5  1479545749              3.688556   
96460     610   160527     4.5  1479544998              3.688556   
96461     610   160836     3.0  1493844794              3.688556   
96462     610   163937     3.5  1493848789              3.688556   
96463     610   163981     3.5  1493850155              3.688556   

       avg_rating_of_movie  
0                  3.92093  
1                  3.92093  
2                  3.92093  
3                  3.92093  
4                  3.92093  
...                    ...  
96459              2.50000  
96460              4.50000  
96461              3.00000  
96462              3.50000  
96463              3.50000  

[96464 rows x 6 columns]

In [ ]:
X_train = train_set[['avg_rating_of_person','avg_rating_of_movie']].to_numpy()
X_train

array([[4.36637931, 3.92093023],
       [3.63636364, 3.92093023],
       [3.23026316, 3.92093023],
       ...,
       [3.68855607, 3.        ],
       [3.68855607, 3.5       ],
       [3.68855607, 3.5       ]])

In [ ]:
y_train = train_set[['rating']].to_numpy()
y_train

array([[4. ],
       [4. ],
       [4.5],
       ...,
       [3. ],
       [3.5],
       [3.5]])

In [ ]:
ratings_valid

userId  movieId  rating   timestamp
0          4       45     3.0   986935047
1          4       52     3.0   964622786
2          4       58     3.0   964538444
3          4      222     1.0   945629040
4          4      247     3.0   986848894
...      ...      ...     ...         ...
2349     561   139385     3.5  1491092337
2350     561   146656     3.5  1491095479
2351     561   149406     3.5  1491091520
2352     561   160438     2.0  1491091498
2353     561   166528     4.0  1491095045

[2354 rows x 4 columns]

In [ ]:
valid_set = pd.merge(ratings_valid,avg_rating_of_person,on='userId')
valid_set = pd.merge(valid_set,avg_rating,on='movieId')
valid_set

userId  movieId  rating   timestamp  avg_rating_of_person  \
0          4       45     3.0   986935047              3.588235   
1        217       45     2.0   955943999              2.784679   
2          4       52     3.0   964622786              3.588235   
3         57       52     3.0   969753586              3.392208   
4        402       52     3.0   849598217              3.921053   
...      ...      ...     ...         ...                   ...   
2349     480    47644     3.5  1179162422              3.316810   
2350     558     3824     5.0  1035416023              3.902439   
2351     558     3831     5.0  1035415531              3.902439   
2352     561     2422     2.5  1491094498              3.400480   
2353     561   106002     2.5  1491091525              3.400480   

      avg_rating_of_movie  
0                3.366667  
1                3.366667  
2                3.520000  
3                3.520000  
4                3.520000  
...                   ...  
2349             2.916667  
2350             2.150000  
2351             3.800000  
2352             1.692308  
2353             3.500000  

[2354 rows x 6 columns]

In [ ]:
X_valid = valid_set[['avg_rating_of_person','avg_rating_of_movie']].to_numpy()
X_valid

array([[3.58823529, 3.36666667],
       [2.78467909, 3.36666667],
       [3.58823529, 3.52      ],
       ...,
       [3.90243902, 3.8       ],
       [3.40047962, 1.69230769],
       [3.40047962, 3.5       ]])

In [ ]:
y_valid = valid_set[['rating']].to_numpy()
y_valid

array([[3. ],
       [2. ],
       [3. ],
       ...,
       [5. ],
       [2.5],
       [2.5]])

In [ ]:
#train model
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

LinearRegression()

In [ ]:
def prediction_df(input_df):
    # get mean of each movie and person
    df = pd.merge(input_df,avg_rating_of_person,on='userId')
    df = pd.merge(df,avg_rating,on='movieId')

    X = df[['avg_rating_of_person','avg_rating_of_movie']].to_numpy()
    # model prediction
    y = linear_model.predict(X)

    # get only necessary columns of data frame
    output_df = df.drop(['timestamp','avg_rating_of_person','avg_rating_of_movie'],axis=1)
    output_df['prediction'] = y
    return output_df

In [ ]:
new_df = prediction_df(ratings_valid)
new_df

userId  movieId  rating  prediction
0          4       45     3.0    3.446328
1        217       45     2.0    2.840438
2          4       52     3.0    3.577991
3         57       52     3.0    3.430184
4        402       52     3.0    3.828939
...      ...      ...     ...         ...
2349     480    47644     3.5    2.855270
2350     558     3824     5.0    2.638528
2351     558     3831     5.0    4.055331
2352     561     2422     2.5    1.867039
2353     561   106002     2.5    3.419247

[2354 rows x 4 columns]

In [ ]:
mean_squared_error(linear_model.predict(X_valid),y_valid)

0.7331235463242868

In [ ]:
mean_squared_error(new_df['rating'],new_df['prediction'])

0.7331235463242868